Gate lastResourceOnlyWatchFacePackageName with a latch
This should ensure the test doesn't fail due to
kotlin.UninitializedPropertyAccessException: lateinit property
lastResourceOnlyWatchFacePackageName has not been initialized.

Test: Presubmit
Bug: 290179105
Change-Id: I30853cf8b688eb91c3c4fdb90413c708f4a6488b