Add API check to avoid NoClassDefFoundError.
Althought A11yActionCompat doesn't support before API level 21,
applications using A11yActionCompat is still able to run on older
platforms (down to minSdkVersion). At that situation, applications
would try to create an object of A11yAction, but this class doesn't
exist before API level 21.

Bug: 119779779
Test: unit test

Change-Id: I7cd24401a1ae691db7964eaa95128d426d200ba0