Fix robolectric test failure by using another  lifecycle library
Using MutableLiveData which in androidx.lifecycle:lifecycle-livedata:2.1.0.

aosp/1057370 will cause some robolectric test fail.
For example ImageAnalysisTest will get following failure:

    [Robolectric] androidx.camera.core.ImageAnalysisTest.blockingAnalyzerClosed_imageNotAnalyzed: sdk=21; resources=binary

    java.lang.NoSuchMethodError: androidx.lifecycle.MutableLiveData.<init>(Ljava/lang/Object;)V

Because in aosp/1057370, it will initiate MutableLiveData object with specific value.

Bug: 122536450
Test: manual with emulator, presubmit
Change-Id: I30a439faf7cec4a132f582730f784ca006458b0c