Catch `NoClassDefFoundError`s for Trace.
* This is because `android.os.Trace` was only introduced in API 18.

Fixes: b/154805833, b/154804973
Test: Existing unit tests pass
Change-Id: I112dc4abd903154e3981c092725770873ec79234