Fix NoClassDefFoundError in pipe-integration tests
*) Issue happen on the API level < 24 devices
*) The libs.kotlinCoroutinesGuava depends on guava:31.0.1-jre
which references Java 1.8. It makes TRUTH lib changes
its dependency from guava:28.1-android -> 31.0.1-jre as well.
guava:31.0.1-jre causes the NoClassDefFoundError in TRUTH lib
at API level < 24 devices since java 1.8 doesn't support
API < 24 environment.

*) Use internal project ":concurrent:concurrent-futures-ktx"
to replace libs.kotlinCoroutinesGuava in build.gradle file
to prevent from an indirect dependency on "guava:31.0.1-jre"

Bug: 233742145
Test: InitializationTest
Change-Id: I676670854b57daceaafe42b7046ed26bb1004b4a