Fix VersionedParcelable classes.
The libary exported with  ./gradlew partiallyDejetifyArchive didn't have
the required *Parcelizer classes, so trying to serialize them crashed
with:
    Process: com.google.postnotifications, PID: 14080
    java.lang.RuntimeException: OngoingActivityData does not have a Parcelizer
        at androidx.versionedparcelable.VersionedParcel.writeVersionedParcelableCreator(VersionedParcel.java:1045)
	...

Adding the annotation process to the build generated them, but some
changes were needed for them to compile, since the generated classes
create a new empty object and then set the fields, all
VersionedParcelable classes need (with at least package visibility):
* A constructor with no parameters (and hence can't be abstract).
* Non-final fields.

Also, LocusIdCompat is not Parcelable and not recognized by the VersionedParcelable compiler.

Actually, I'm a bit concerned about VersionParcelable. Looking at other uses of it in AndroidX I found:
http://cs/aosp-androidx/media2/session/src/main/java/androidx/media2/session/MediaSession.java?l=1008
Note the WARNING. And http://doc/1k-uPeNngxHT3t9chfyZjg-LzCK7U00orHnbk5k9m4t0

Relnote: N/A
Bug: 172807623
Test: Generated the archive and tested against the test apps on G3.
Change-Id: I1be8c0ddc348eaae279ef14ee1d3ec2f9f4d3f27