more explanation about build_log_simplifier
- busytown/impl/build.sh moving the reproduction command into stderr, so it shows up in build_error.log
- now explaining more details about making exemption lines appropriately generalized
- explicitly reminding the user to download the exemptions file from the build server
- explicitly calling out that "-Pandroidx.validateNoUnrecognizedMessages" is what enables this validation

Bug: 169058840
Test: ./busytown/impl/build.sh :help -Pandroidx.validateNoUnrecognizedMessages >/dev/null # and see that the output is:

  Error: build_log_simplifier.py found 16 new messages found in /usr/local/google/workspace/aosp-androidx-git/out/dist/ui/gradle.log.

  Please fix or suppress these new messages in the tool that generates them.
  If you cannot, then you can exempt them by doing:

    1. cp /usr/local/google/workspace/aosp-androidx-git/out/dist/ui/gradle.log.ignore /usr/local/google/workspace/aosp-androidx-git/frameworks/support/development/build_log_simplifier/messages.ignore # or, if this script is running on the build server, you may download this file from there
    2. modify the new lines to be more generalized (they are regular expressions) if it is more important to preemptively exempt similar messages than to be notified of new, similar messages

  Note that if you exempt these messages by updating the exemption file, this will suppress these messages in the output of CI builds but not in Android Studio.
  Additionally, adding more exemptions to this exemption file will cause the build to run more slowly than fixing or suppressing the message where it is generated.

  Build log validation, enabled by the argument -Pandroidx.validateNoUnrecognizedMessages, failed

  Failed: OUT_DIR=out/ui DIST_DIR=/usr/local/google/workspace/aosp-androidx-git/frameworks/support/busytown/impl/../../../../out/dist/ui ANDROID_HOME=./prebuilts/fullsdk-linux frameworks/support/ui/gradlew -p frameworks/support/ui --stacktrace -Pandroidx.summarizeStderr :help -Pandroidx.validateNoUnrecognizedMessages

Change-Id: I47884b0caa5d8839091571fac8a1491960576558